In [59]:
num_1=4
num_2=2
print(num_1+num_2)

6


In [60]:
tup_1=(1,2,3)
tup_2=(1,1,1)
print(tup_1+tup_2) #operação considera objeto inteiro pra tupla e lista (add ao final, concatena)

#mesma coisa da conta acima:
tup_1+=tup_2 

(1, 2, 3, 1, 1, 1)


In [61]:
#para converter obj em lista, mas tup_1 ainda é uma tupla, só 
listtup=list(tup_1)
print(listtup)

listtup[2]+=2 #a cada vez que roda a célula, vai fazer a operação (se fizer fora da celula onde ta instanciando)
listtup

[1, 2, 3, 1, 1, 1]


[1, 2, 5, 1, 1, 1]

In [62]:
listtup+=tup_1
listtup

[1, 2, 5, 1, 1, 1, 1, 2, 3, 1, 1, 1]

In [63]:
#lista e tupla faz indexação automática e em ordem, então dá pra fazer as operações
#dicionário tem indexação manual, nao tem uma ordem
dic1={'a':1,'b':2,'c':3}
dic2={'aa':10,'bb':20}
print(dic1,dic2)

{'a': 1, 'b': 2, 'c': 3} {'aa': 10, 'bb': 20}


In [64]:
#para concatenar dicionarios:
dic1.update(dic2)
dic1

{'a': 1, 'b': 2, 'c': 3, 'aa': 10, 'bb': 20}

In [65]:
import numpy as np

In [66]:
array=np.array(listtup)
array

array([1, 2, 5, 1, 1, 1, 1, 2, 3, 1, 1, 1])

In [67]:
array[2]+=2
array

array([1, 2, 7, 1, 1, 1, 1, 2, 3, 1, 1, 1])

In [68]:
array*=2
array

array([ 2,  4, 14,  2,  2,  2,  2,  4,  6,  2,  2,  2])

Lista e tupla se somar, vai olhar o obj inteiro e concatenar. 
Pra somar elemento por elemento, precisa indexar > da pra usar estrutura de repetição

Array se somar, vai somar a cada elemento
Para concatenar usa .concat

In [69]:
#inserir elemento na ultima posição > nao instanciei obj aqui
np.insert(arr=array, obj=0, values=[1,1,2])

array([ 1,  1,  2,  2,  4, 14,  2,  2,  2,  2,  4,  6,  2,  2,  2])

In [70]:
array.shape

(12,)

In [72]:
array.reshape(2,6)

array([[ 2,  4, 14,  2,  2,  2],
       [ 2,  4,  6,  2,  2,  2]])

In [78]:
#se eu quiser 6 linhas e nao importa quantas colunas:
arr2=array.reshape(4,-1)
arr2

array([[ 2,  4, 14],
       [ 2,  2,  2],
       [ 2,  4,  6],
       [ 2,  2,  2]])

In [ ]:
import pandas as pd

In [79]:
df=pd.DataFrame(arr2)
df

,0,1,2
0,2,4,14
1,2,2,2
2,2,4,6
3,2,2,2


In [ ]:
#da pra alterar valor especifico
#tbm existe zeros_like
arr_ones=np.ones_like(df)
arr_ones[1,1]=222
arr_ones

array([[  1,   1,   1],
       [  1, 222,   1],
       [  1,   1,   1],
       [  1,   1,   1]])

In [ ]:
#0 é f e 1 é v, funciona pra int e float
0==False

True

In [83]:
1<=3==3

True

In [85]:
# metodos values, items, keys (obj.metodo())
#dicionario nao compara maior/menor, mas se pedir comom items ele retorna como tupla, ai dá
{'a':1,'b':2}.items() <= {'a':1,'b':2}.items()

True

In [92]:
#aleatorio com media 0 e dp 1 > terá 10 valores entre -1 e 1 com dist normal
#PRIMEIRO TESTA SE O QUE QUERO FAZER FUNCIONA E DEPOIS QUE DER, INSTANCIO O OBJ PRA ECONOMIZAR RAM
arr_rand=np.random.normal(0,1,1000).reshape(-1,10)
print(arr_rand)
arr_rand[:2]

[[ 0.99949988  1.48059584 -1.02451155 -0.8614114  -0.27996923 -2.85507207
   0.1047417   1.1344126  -0.31293796 -0.34346681]
 [-1.20196757 -0.02035361 -0.5311331  -0.22103344 -0.41925933  0.89302975
   0.90020952  0.27964719  0.26177091 -0.67754126]
 [ 0.18850497  1.10443981  2.42578467  1.18177855  0.72258208 -1.23878656
   0.70823512  1.92554111 -1.33021764  1.93347407]
 [ 0.67589444 -1.0017361  -0.44258861  0.19743198 -0.4752975  -0.33669858
  -0.51576935 -0.31478928  1.44281144 -1.02488619]
 [ 0.35438948 -0.41689013 -0.48146264  1.38567486  0.0464263   1.56710423
  -0.43107437 -2.19146306  1.20272403  0.79190185]
 [-1.02028428 -0.123975   -1.05368366  1.22507746  0.86598407  0.8042167
  -1.31321378 -0.28391815  0.2826682   0.13849776]
 [-1.09984609 -1.14965536 -0.82276621 -0.03398387 -0.15932609 -1.67536257
   1.52346367 -0.34952536  0.31778961  1.62427615]
 [-1.30231636  0.37481315 -0.30063741 -0.75139999 -0.66686957  0.45218098
  -0.35100422 -0.26706457 -1.59587904  1.29782654]
 

array([[ 0.99949988,  1.48059584, -1.02451155, -0.8614114 , -0.27996923,
        -2.85507207,  0.1047417 ,  1.1344126 , -0.31293796, -0.34346681],
       [-1.20196757, -0.02035361, -0.5311331 , -0.22103344, -0.41925933,
         0.89302975,  0.90020952,  0.27964719,  0.26177091, -0.67754126]])

In [101]:
np.random.seed(42)
arr_r=np.random.normal(0,1,100).reshape(-1,10)
arr_r2=np.random.normal(0,1,100).reshape(-1,10)

#o [:2] MOSTRA QUE QUERO INDEXAR DO INICIO DO OBJ ATÉ A LINHA 1 (IGNORA O 2), PRA TODAS AS COLUNAS PQ NAO COLOQUEI NENHUMA ALI
#ISSO NAO FUNCIONA PRO CONTRARIO
arr_r[:2]

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
        -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783,
        -0.56228753, -1.01283112,  0.31424733, -0.90802408, -1.4123037 ]])

In [102]:
pd.DataFrame(arr_r) <= pd.DataFrame(arr_r2)

,0,1,2,3,4,5,6,7,8,9
0,False,False,False,False,True,True,True,False,True,False
1,False,True,False,True,True,True,True,False,True,True
2,False,False,True,True,True,True,True,False,True,False
3,False,False,False,True,False,True,False,True,True,False
4,False,True,False,True,True,True,False,False,True,True
5,False,True,False,False,False,False,True,True,False,False
6,False,True,True,True,True,False,True,True,False,False
7,False,False,False,False,True,True,False,True,False,True
8,True,False,False,True,True,True,False,False,False,False
9,False,False,True,False,True,True,False,False,True,False


In [105]:
df1=pd.DataFrame(arr_r) 
df2=pd.DataFrame(arr_r2)
display(df1.head())

,0,1,2,3,4,5,6,7,8,9
0,0.496714,-0.138264,0.647689,1.523030,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.542560
1,-0.463418,-0.465730,0.241962,-1.913280,-1.724918,-0.562288,-1.012831,0.314247,-0.908024,-1.412304
2,1.465649,-0.225776,0.067528,-1.424748,-0.544383,0.110923,-1.150994,0.375698,-0.600639,-0.291694
3,-0.601707,1.852278,-0.013497,-1.057711,0.822545,-1.220844,0.208864,-1.959670,-1.328186,0.196861
4,0.738467,0.171368,-0.115648,-0.301104,-1.478522,-0.719844,-0.460639,1.057122,0.343618,-1.763040


In [108]:
1==1 and 1==3 or 1==1

True

In [107]:
print(1 in [1,2,3])
'1' in [1,2,3]

True


False

In [ ]:
p=1
q=1.0
p is q #também observa classe

False