# Exercício:

## 01 – Cite três vantagens do uso das funções e duas características que toda função deva ter?

R.: Funções tem as vantagens da usabilidade, porque após definidas podem ser importadas para outros códigos; de processamento, pois são blocos de código que são executados apenas quando chamados especificamente e vantagem de correção/ armazenamento, pois reúnem comandos em um único lugar, no qual são corrigidas apenas uma vez se necessário, sem precisar corrigir em cada parte do código onde foi chamada.

Como características de toda função, elas sempre retornam apenas um objeto (ainda que gere vários valores, a saída será por exemplo um objeto composto com esses valores) e devem sempre ser claras e diretas ao máximo para assegurar a vantagem de organização.

## Responda a pergunta do exercício 2 da aula 10, usando funções:<br>
Instancie um objeto da classe NumPy array, contendo 5 valores quantitativos randômicos normalmente distribuídos, com média 10 e desvio padrão 3.<br><br>
Quantos e quais são os valores superiores a 10?

## 02 – Descreva o racional da sua resposta:

R.: Primeiro, para criar esse objeto é preciso importar a biblioteca numpy: import numpy as np

Depois, o método para obter um array de distribuição normal é: np.random.normal()

Dentro dos parenteses, vão os parametros separados por virgula: media, desvio padrao, numero de valores

Para instanciação do objeto: array_rand=np.random.normal(10,3,5)

Segundo, para responder a pergunta, será criada uma função (contagem) que terá dois parâmetros: o objeto que deve ser um array (ele que será avaliado pela função) e um limite: será um valor float (também poderia ser um inteiro, mas optei por float para não ser muito limitante. Esse valor será o parâmetro de comparação dos valores do objeto na condicional)

Então, dentro da função pode ser usada a mesma estrutura de repetição do exercício anterior, que vai partir de um contador em zero e uma lista vazia 

Ao longo de um range definido pelo numero de elementos do objeto, vai verificar uma condição que se dá pelo if.

Se o valor observado for maior que o limite, será acrescentado esse valor à lista e adicionado 1 ao contador. 

Para adicionar valores à lista pode ser usado o método append() levando em conta que são valores float e a indexação do loop a cada volta

Então, a repetição se dá sucessivamente até o final, quando vai devolver fora do loop a contagem de valores maiores que o limite e a lista com estes valores.

## 03 – Desenhe o fluxograma da resposta:

<img src="disciplina python\3_lista12.jpeg" width="400" />

## 04 – Escreva o programa em Python:

In [1]:
import numpy as np
array_rand=np.random.normal(10,3,5)
print(array_rand)

def contagem(obj:np.array, limite:float):
    contador=0
    lista=[]
    for i in range(len(obj)):
        if obj[i] > limite:
            contador+=1
            lista.append(float(obj[i]))
    print(f'número de elementos maiores que 10: {contador}')
    print(f'valores maiores que 10: {lista}')


[13.75258917  6.17486357  5.51153237 11.21269394 12.51463152]


In [2]:
contagem(array_rand,10)

número de elementos maiores que 10: 3
valores maiores que 10: [13.752589166143718, 11.21269394003728, 12.51463152255177]


## 05 – Seria possível, com o racional proposto, saber quantos e quais valores são superiores a 20? Porque?

In [3]:
#Sim, porque o limite da condicional é um parâmetro da função, que pode ser definido no momento em que ela é chamada:
contagem(array_rand,20)

número de elementos maiores que 10: 0
valores maiores que 10: []


## Desenvolva um programa de computador que retorne a média de um conjunto de valores.

## 06 – Descreva o racional da sua resposta:

R.: Será definida uma função (medias()), na qual, como conjunto de valores, vou considerar tuplas e listas como aceitáveis na função (objeto) e ela retornará um valor float como output (já que será o resultado de uma divisão): def medias(obj:list|tuple)->float.

Dentro da função, serão somados (sum()) os itens da lista ou tupla e divididos pelo número de itens (/len(obj))

## 07 – Desenhe o fluxograma da resposta:

<img src="disciplina python\7_lista12.jpeg" width="400" />

## 07 – Escreva o programa em Python:

In [33]:
def medias(obj:list|tuple)->float:
    med = sum(obj)/len(obj)
    return med

In [37]:
#testando a função em uma tupla não instanciada:
medias((1,3,5,7,9))

5.0

## 09 – Desenvolva um programa de computador que retorne a divisão de dois objetos simples. Seu programa deve ser capaz de reconhecer a classe destes objetos e o valor, antes de retornar ao usuário.

In [48]:
def divisao(obj1:int|float,obj2:int|float)->float:
    if type(obj1) not in (int, float) or type(obj2) not in (int, float):
        raise TypeError("Os valores devem ser int ou float")
    
    # Evitar divisão por zero
    if obj2 == 0:
        raise ZeroDivisionError("Divisão por zero não é permitida")
    
    # Mostrando informações antes do retorno
    print(f'obj1: valor={obj1}, tipo={type(obj1).__name__}')
    print(f'obj2: valor={obj2}, tipo={type(obj2).__name__}')
    
    div = obj1 / obj2
    
    return div

In [53]:
divisao(27,3)

obj1: valor=27, tipo=int
obj2: valor=3, tipo=int


9.0

## 10 – Desenvolva um programa de computador que retorne a divisão de dois objetos compostos. Seu programa deve ser capaz de reconhecer a classe destes objetos e o valor, antes de retornar ao usuário.

In [85]:
def divisao_arrays(obj1:np.ndarray, obj2:np.ndarray):
    
    if type(obj1) != np.ndarray or type(obj2) != np.ndarray:
        raise TypeError("Os objetos devem ser arrays numpy")
    
    # Verificar formato
    if obj1.shape != obj2.shape:
        raise ValueError("Os arrays devem ter o mesmo formato")
    
    print(f'obj1: tipo={type(obj1).__name__}, valores=\n{obj1}')
    print(f'obj2: tipo={type(obj2).__name__}, valores=\n{obj2}')
    
    # Verificar divisão por zero
    if np.any(obj2 == 0):
        print("Aviso: há divisão por zero no array!")
    
    resultado = obj1 / obj2
    
    return resultado

In [86]:
arr1 = np.random.randint(0, 20,(5, 5))
arr2=np.random.randint(1,20,(5,5))
divisao_arrays(arr1,arr2)

obj1: tipo=ndarray, valores=
[[14  5 13 11  5]
 [16 17  5  2 14]
 [15 18 15  2 11]
 [ 9  7  6 18  5]
 [ 3  8 19 10 15]]
obj2: tipo=ndarray, valores=
[[19  2  4 10  5]
 [ 7  6 17  4 17]
 [ 7 11  7  9  1]
 [ 8 19 15 15 13]
 [ 1  4 10  8 16]]


array([[ 0.73684211,  2.5       ,  3.25      ,  1.1       ,  1.        ],
       [ 2.28571429,  2.83333333,  0.29411765,  0.5       ,  0.82352941],
       [ 2.14285714,  1.63636364,  2.14285714,  0.22222222, 11.        ],
       [ 1.125     ,  0.36842105,  0.4       ,  1.2       ,  0.38461538],
       [ 3.        ,  2.        ,  1.9       ,  1.25      ,  0.9375    ]])